
import { User, Role, UserCategory } from './types';

export const INITIAL_USERS: User[] = [
  { id: '999999999', name: 'SUPER ADMINISTRADOR', role: Role.INSTRUCTOR_MEDIALAB }, // Acceso de respaldo
  { id: '1076906283', name: 'RUBER ARIEL MONTEALEGRE PAREDES', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1010150164', name: 'KENNETH FERNANDO RESTREPO HERNANDEZ', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1048994103', name: 'ESTHEFANY ESTRADA RIZO', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1075793647', name: 'JHOAN SEBASTIAN CUENCA CAICEDO', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1077224761', name: 'MARIA FERNANDA HERRERA RIVERA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1076905493', name: 'LUISA FERNANDA AGUILAR MEDINA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1080189486', name: 'CARLOS ANDRES GUTIERREZ VILLARREAL', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1193079898', name: 'MARIA PAULA PEÑA POLANIA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1075791555', name: 'NICOLAS URIBE REY', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '55178479', name: 'SANDRA MARCELA QUINTERO ARIAS', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1117489567', name: 'LEIDI YULIED RAMOS MONROY', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1193376665', name: 'DANNA VALENTINA PERDOMO HERNANDEZ', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1075279475', name: 'JESUS RICARDO CUELLAR SANCHEZ', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1000992150', name: 'JEISON DAVID TACUMA CASTILLO', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1076503351', name: 'DANIEL ALBERTO ALVAREZ DUSSAN', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1193044406', name: 'NATALY LOZANO CASTRO', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1076501821', name: 'MARIA SARAY SOLANO OCHOA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1077226939', name: 'JUAN ESTEBAN BUSTOS ANACONA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1076502814', name: 'MARIANA FALLA DURAN', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1007163090', name: 'VANESSA ALEJANDRA MEDINA MENESES', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1077227049', name: 'JUAN DAVID ARIAS ROJAS', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1077723439', name: 'ANASOL SALAZAR ALARCON', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1075272159', name: 'NORMA YOHANA ORJUELA GONZALEZ', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1075284468', name: 'CRISTIAN ANDRES PADILLA ORTIZ', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1077226006', name: 'NICOLAS SALAS POLANIA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1193433235', name: 'RAUL ANDRES ROCHA PEÑA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1075212110', name: 'DANIELA OSORIO MONJE', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1077225921', name: 'MIGUEL ANGEL PERDOMO DURAN', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1077224121', name: 'NOAH MATOS VASQUEZ', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1014667471', name: 'DANNA SOFIA CASTRO HERNANDEZ', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1076906370', name: 'ANA ISABELA VILLARREAL MONTEALEGRE', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1004156087', name: 'MAYRA LIZZETTE RIVERA ARRUBLA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1075791782', name: 'EVELIN CAROLINA SANCHEZ MEDINA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1003895782', name: 'MARIA JOSE MEDINA DUARTE', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1003828742', name: 'YURY YASLEIDY VELASQUEZ TRUJILLO', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1076905797', name: 'JUAN FELIPE BAUTISTA USECHE', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1076904596', name: 'KAREN TATIANA ERAZO MONTES', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1029880680', name: 'TATIANA YUNDA CORTES', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1075319029', name: 'YEHIMY CAROLINA RAMIREZ SUAREZ', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1075295862', name: 'LUIS EDUARDO RODRIGUEZ BERNAL', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1030568904', name: 'HELBERT JOHANN AVILA MORENO', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1080293927', name: 'JESUS DANIEL PENCUE TEJADA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1077725140', name: 'MARIANA CERQUERA ALVARADO', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1078749426', name: 'SAMUEL DAVID VARGAS RIASCOS', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1075321998', name: 'NATALIA NARVAEZ MEDINA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1077228135', name: 'VALENTINA HORTA JEJEN', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1075792531', name: 'NICOLL SOFIA GUILOMBO VARGAS', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1003953024', name: 'JUAN NICOLAS MORENO PAREDES', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1079176201', name: 'ALEX DUVAN FIERRO OLAYA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1075219718', name: 'LAURA ALEXANDRA NINCO CALDERON', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1077722852', name: 'MICHELL VELASQUEZ RUBIO', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1075307870', name: 'DIEGO ALEJANDRO ARGUELLO BONILLA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1084922635', name: 'ISABella SILVA RIVERA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1083864252', name: 'BRAYAN STIVEN CORREAL ORTIZ', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1129844901', name: 'JABNEEL TIMOTEO MARIN VERA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1109662681', name: 'BRAYAN ANDRES BOLAÑOS PEREZ', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1076906011', name: 'PAULA ANDREA CASTAÑEDA VASQUEZ', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1077856321', name: 'YEIMI LICED MACIAS PERDOMO', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1118293427', name: 'HEIDY ARLETH RAMIREZ ROJAS', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1075244717', name: 'SHARIT ROJAS MEDINA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1029881622', name: 'LIYEN KATERIN GONZALEZ RODRIGUEZ', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1029880785', name: 'DANNA VALENTINA PERDOMO JAVELA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1076907073', name: 'MARIAN ZURETH HERNANDEZ DIAZ', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1012339933', name: 'VICTOR MANUEL MENSA COMETA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1077722372', name: 'PAULO SERGIO LOSADA RIVERA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1076501696', name: 'KARLA SOFIA SOTO QUIMBAYA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1075311655', name: 'JULIAN SANTIAGO DIAZ PATIO', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1029882599', name: 'ALLISON DAYANA GAMBOA FONSECA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1023378542', name: 'JOSE ALEJANDRO AREVALO GUTIERREZ', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1077851528', name: 'DIDIER ANDRES ACERO NARVAEZ', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1076503143', name: 'VALENTINA CHANTRE CUELLAR', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1014476862', name: 'JUAN ESTEBAN RAMIREZ GONZALEZ', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1003804524', name: 'JEAM PIERE VALENCIA RIVERA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1076903329', name: 'LAURA VALENTINA GUZMAN MEDINA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1077228388', name: 'ANA SOFIA VALENZUELA MEDINA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1075226769', name: 'MARIA JOSE GUEVARA TORRES', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1075214924', name: 'KAREN SOFIA JIMENEZ MOSQUERA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1075244506', name: 'MATIAS GOMEZ MONTENEGRO', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1082125825', name: 'JHON SEBASTIAN FERNANDEZ VARGAS', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1075242050', name: 'MICHAEL JORDAN ROJAS PUENTES', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1070595500', name: 'JOSE DAVID CARDOSO PATIÑO', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1003813248', name: 'DANIEL STIVEN RODRIGUEZ POLANIA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1081404354', name: 'KAREN YULIANA MEDINA SALAZAR', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1014659430', name: 'ANA MARIA PACHON NARVAEZ', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1077847486', name: 'NICOLAS FREDERY ALVAREZ PARRA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1079534321', name: 'VALENTINA FORERO ROJAS', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1006517385', name: 'PAULA ANDREA CRUZ OTALORA', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '1077723484', name: 'DIEGO ALEJANDRO ROJAS MORALES', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '79653359', name: 'PAULO CESAR LUNA OCHOA', role: Role.INSTRUCTOR_MEDIALAB },
  { id: '1075229132', name: 'JOHAN EDISSON RUBIANO GUTIERREZ', role: Role.INSTRUCTOR_MEDIALAB },
  { id: '80123456', name: 'CARLOS ANDRES RAMIREZ', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '52987654', name: 'SOFIA GOMEZ PEREZ', role: Role.USUARIO_MEDIALAB, category: UserCategory.APRENDIZ },
  { id: '36304398', name: 'EDNA GORETTI CARVAJAL FAJARDO', role: Role.INSTRUCTOR_MEDIALAB },
  { id: '7705206', name: 'CARLOS ANDRÉS FERNÁNDEZ GONZÁLEZ', role: Role.INSTRUCTOR_MEDIALAB },
  { id: '92548297', name: 'ALBERTO ENRIQUE OVIEDO BUELVAS', role: Role.INSTRUCTOR_MEDIALAB },
  { id: '1075217951', name: 'MIGUEL ÁNGEL CHARRY SUAREZ', role: Role.INSTRUCTOR_MEDIALAB },
];
